### ISSUE TITLE
VSCode extension creates new files per interface

### ISSUE THREAD

**Issue by tme321** [MariusAlch/json-to-ts#4]
This is more a feature for the vs code extension specifically, but it would be nice if instead of pasting into the current file it would create a new file named after the interface per interface it parses out of a response.  Especially if I could specify a root directory to put these interface definitions inside of.

**Comment by MariusAlch** [comment]
Okay so lets start by saying this suggestion might be very useful to some, but would be noise to bigger portion of users, for a simple reason that this is very opinionated topic. 

Some people like to have all interfaces in one file, some would like to have file per each interface. Some  would like to keep the interfaces in the same source file its being referenced, some would like to have types in root directory and so on.

So ill have to refuse putting this in extension simply because there is no way to get this right for every user without creating lots of configuration options which 99% of the users wont use and also this takes away simplicity and single responsibility of the extension.

I'm closing this for now, but if this get some more traction maybe I'll have to reconsider my opinion in the future.

**Comment by tme321** [comment]
That's fair.  Thanks for considering it though.
