### ISSUE TITLE
incorrect optional on null

### ISSUE THREAD

**Issue by shakyShane** [MariusAlch/json-to-ts#5]
given this input

```json
{
  "alive": null
}
```

the expected output would be

```ts
interface RootObject {
  alive: null;
}
```

but it actually produces 

```ts
interface RootObject {
  alive?: any;
}
```

**Comment by shakyShane** [comment]
I think there's generally a problem with nulls, as this is also incorrect

```
{
  "users": [{"name": "shane", "age": null}]
}
```

gives 

```
interface RootObject {
  users: User[];
}

interface User {
  name: string;
  age?: any;
}
```

**Comment by MariusAlch** [comment]
This is by design. 
It makes sense from Typescript perspective to set type to null since this is the most precise type typescript has to define this field, but looking from real world perspective, a null field probably means that  "something that should be here is not present"
```
{
name: "Bob",
age: 20,
address: null
}
```
 
so setting a field 
```
address?: any
```
is saying there is a field "address", switch might be not present, and we dont know its type


```
address: null | any;
```
is another option, but I choose the first which is more autocomplete friendly. In this case using `address.street` will give me an error, in first example it wont

**Comment by shakyShane** [comment]
but using an optional is incorrect - the property is present, it's only value that is possibly unknown, so your last example would be preferable.

I addressed this issue by allowing multiple inputs to be merged - then you can correctly portray the options

**Comment by MariusAlch** [comment]
True that, but I have my explanation, why I avoided
```
address: null | any;
```
